export const SET_REVERSE_OPENED = 'SET_REVERSE_OPENED';
export const HEADER_SET_TITLE = 'HEADER_SET_TITLE';
export const SAVE_TO_LOCAL_STORAGE = 'SAVE_TO_LOCAL_STORAGE';
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SET_LOCALSTORAGE = 'SET_LOCALSTORAGE';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';